### ISSUE TITLE
writeos - query

### ISSUE THREAD

**Issue by GoelBiju** [vkhristenko/test-cpp#1]
@vkhristenko I saw your post on the wyoos forum regarding the "Hello World" not printing when booting the iso (posted last year). I am facing the same issue and I wanted to ask if you managed to find a solution?

**Comment by vkhristenko** [comment]
Hey Goel! For that particular example i was not able to make it work. given my goal was more to understand how to get things from __zero__ rather than writing in c++ i switched.

Then, i restored to using assembly directly + c. 
https://github.com/vkhristenko/test-os/tree/master/os_dev_book/kernel

I've tested this guy with qemu and works well!

the book itself i think i found here: https://news.ycombinator.com/item?id=8380822

Hope this helps u!

**Comment by GoelBiju** [comment]
Thank you very much @vkhristenko , I appreciate the help!
